
POST http://127.0.0.1:5000/github
Content-Type: application/json

{
  "action": "edited",
  "issue": {
    "url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/62",
    "repository_url": "https://api.github.com/repos/panu00x/OCR_Issue",
    "labels_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/62/labels{/name}",
    "comments_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/62/comments",
    "events_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/62/events",
    "html_url": "https://github.com/panu00x/OCR_Issue/issues/62",
    "id": 487427793,
    "node_id": "MDU6SXNzdWU0ODc0Mjc3OTM=",
    "number": 62,
    "title": "svsd",
    "user": {
      "login": "panu00x",
      "id": 42166587,
      "node_id": "MDQ6VXNlcjQyMTY2NTg3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/42166587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/panu00x",
      "html_url": "https://github.com/panu00x",
      "followers_url": "https://api.github.com/users/panu00x/followers",
      "following_url": "https://api.github.com/users/panu00x/following{/other_user}",
      "gists_url": "https://api.github.com/users/panu00x/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/panu00x/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/panu00x/subscriptions",
      "organizations_url": "https://api.github.com/users/panu00x/orgs",
      "repos_url": "https://api.github.com/users/panu00x/repos",
      "events_url": "https://api.github.com/users/panu00x/events{/privacy}",
      "received_events_url": "https://api.github.com/users/panu00x/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1511046343,
        "node_id": "MDU6TGFiZWwxNTExMDQ2MzQz",
        "url": "https://api.github.com/repos/panu00x/OCR_Issue/labels/area-Serialization",
        "name": "area-Serialization",
        "color": "ededed",
        "default": false
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2019-08-30T11:11:34Z",
    "updated_at": "2019-08-30T11:26:18Z",
    "closed_at": null,
    "author_association": "OWNER",
    "body": "dcsdcvrfv"
  },
  "changes": {
    "body": {
      "from": "dcsdcvr"
    }
  },
  "repository": {
    "id": 203288511,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDMyODg1MTE=",
    "name": "OCR_Issue",
    "full_name": "panu00x/OCR_Issue",
    "private": true,
    "owner": {
      "login": "panu00x",
      "id": 42166587,
      "node_id": "MDQ6VXNlcjQyMTY2NTg3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/42166587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/panu00x",
      "html_url": "https://github.com/panu00x",
      "followers_url": "https://api.github.com/users/panu00x/followers",
      "following_url": "https://api.github.com/users/panu00x/following{/other_user}",
      "gists_url": "https://api.github.com/users/panu00x/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/panu00x/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/panu00x/subscriptions",
      "organizations_url": "https://api.github.com/users/panu00x/orgs",
      "repos_url": "https://api.github.com/users/panu00x/repos",
      "events_url": "https://api.github.com/users/panu00x/events{/privacy}",
      "received_events_url": "https://api.github.com/users/panu00x/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/panu00x/OCR_Issue",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/panu00x/OCR_Issue",
    "forks_url": "https://api.github.com/repos/panu00x/OCR_Issue/forks",
    "keys_url": "https://api.github.com/repos/panu00x/OCR_Issue/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/panu00x/OCR_Issue/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/panu00x/OCR_Issue/teams",
    "hooks_url": "https://api.github.com/repos/panu00x/OCR_Issue/hooks",
    "issue_events_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/events{/number}",
    "events_url": "https://api.github.com/repos/panu00x/OCR_Issue/events",
    "assignees_url": "https://api.github.com/repos/panu00x/OCR_Issue/assignees{/user}",
    "branches_url": "https://api.github.com/repos/panu00x/OCR_Issue/branches{/branch}",
    "tags_url": "https://api.github.com/repos/panu00x/OCR_Issue/tags",
    "blobs_url": "https://api.github.com/repos/panu00x/OCR_Issue/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/panu00x/OCR_Issue/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/panu00x/OCR_Issue/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/panu00x/OCR_Issue/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/panu00x/OCR_Issue/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/panu00x/OCR_Issue/languages",
    "stargazers_url": "https://api.github.com/repos/panu00x/OCR_Issue/stargazers",
    "contributors_url": "https://api.github.com/repos/panu00x/OCR_Issue/contributors",
    "subscribers_url": "https://api.github.com/repos/panu00x/OCR_Issue/subscribers",
    "subscription_url": "https://api.github.com/repos/panu00x/OCR_Issue/subscription",
    "commits_url": "https://api.github.com/repos/panu00x/OCR_Issue/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/panu00x/OCR_Issue/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/panu00x/OCR_Issue/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/panu00x/OCR_Issue/contents/{+path}",
    "compare_url": "https://api.github.com/repos/panu00x/OCR_Issue/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/panu00x/OCR_Issue/merges",
    "archive_url": "https://api.github.com/repos/panu00x/OCR_Issue/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/panu00x/OCR_Issue/downloads",
    "issues_url": "https://api.github.com/repos/panu00x/OCR_Issue/issues{/number}",
    "pulls_url": "https://api.github.com/repos/panu00x/OCR_Issue/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/panu00x/OCR_Issue/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/panu00x/OCR_Issue/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/panu00x/OCR_Issue/labels{/name}",
    "releases_url": "https://api.github.com/repos/panu00x/OCR_Issue/releases{/id}",
    "deployments_url": "https://api.github.com/repos/panu00x/OCR_Issue/deployments",
    "created_at": "2019-08-20T02:56:21Z",
    "updated_at": "2019-08-27T07:42:41Z",
    "pushed_at": "2019-08-27T03:47:32Z",
    "git_url": "git://github.com/panu00x/OCR_Issue.git",
    "ssh_url": "git@github.com:panu00x/OCR_Issue.git",
    "clone_url": "https://github.com/panu00x/OCR_Issue.git",
    "svn_url": "https://github.com/panu00x/OCR_Issue",
    "homepage": null,
    "size": 2549,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "panu00x",
    "id": 42166587,
    "node_id": "MDQ6VXNlcjQyMTY2NTg3",
    "avatar_url": "https://avatars3.githubusercontent.com/u/42166587?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/panu00x",
    "html_url": "https://github.com/panu00x",
    "followers_url": "https://api.github.com/users/panu00x/followers",
    "following_url": "https://api.github.com/users/panu00x/following{/other_user}",
    "gists_url": "https://api.github.com/users/panu00x/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/panu00x/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/panu00x/subscriptions",
    "organizations_url": "https://api.github.com/users/panu00x/orgs",
    "repos_url": "https://api.github.com/users/panu00x/repos",
    "events_url": "https://api.github.com/users/panu00x/events{/privacy}",
    "received_events_url": "https://api.github.com/users/panu00x/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 1718647,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTcxODY0Nw=="
  }
}